version: '3'
services:
  rethinkdb:
    image: rethinkdb
    ports:
     - "28015:28015"
     - "8080:8080"
    volumes:
     - ./tmp/rethinkdb/data:/data
    command: rethinkdb --bind all
  logstash:
    build: .
    volumes:
      - ./:/srv/code
      - ./spec/support/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./spec/support/pipeline/:/usr/share/logstash/pipeline/